Resources:
  ServiceDiscoveryPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ${self:provider.stage}-ServiceDiscoveryPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - servicediscovery:DiscoverInstances
            Resource: '*'
      Roles:
        - Ref: ServerlessAppRole
  LambdaSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security Group for KMS Lambda functions'
      SecurityGroupEgress:
        - CidrIp: '0.0.0.0/0'
          IpProtocol: -1
          FromPort: 0
          ToPort: 65535
      VpcId: ${env:VPC_ID}

  ServerlessAppRole:
    Type: "AWS::IAM::Role"
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      PermissionsBoundary:
        Fn::Join: [
          "", [
            "arn:aws:iam::",
            {
              "Ref": "AWS::AccountId"
            },
            ":policy/NGAPShRoleBoundary"
          ]
        ]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - states.amazonaws.com
                - events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: KMSLambdaBase
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: '*'
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: '*'

# Output the following resources so that other stacks can access the values
Outputs:
  KMSLambdaSecurityGroup:
    Value:
      Ref: LambdaSecurityGroup
    Export:
      Name: ${self:provider.stage}-LambdaSecurityGroup

  KMSServerlessAppRole:
    Description: Role used to execute commands across the serverless application
    Value:
      Fn::GetAtt:
        - ServerlessAppRole
        - Arn
    Export:
      Name: ${self:provider.stage}-KMSServerlessAppRole
