/**
 * @fileoverview Generates SPARQL PREFIX declarations from predefined RDF namespaces.
 * @module prefixes
 */

import { namespaces } from '@/shared/constants/namespaces'

/**
 * A string containing SPARQL PREFIX declarations for all namespaces defined in the namespaces module.
 * Each PREFIX declaration is on a new line.
 *
 * This constant is generated by:
 * 1. Converting the namespaces object to an array of [key, value] pairs
 * 2. Mapping each pair to a PREFIX declaration string
 * 3. Joining all declarations with newline characters
 *
 * @type {string}
 *
 * @example
 * // The generated string will look like:
 * // PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
 * // PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
 * // ...
 */
export const prefixes = Object.entries(namespaces)
  .map(([key, value]) => `PREFIX ${key.replace('@xmlns:', '')}: <${value}>`)
  .join('\n')

export default prefixes
